name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

 build_and_push:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name:  Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USER_NAME }}/ai_service:latest .

      - name:  Tag and Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USER_NAME }}/ai_service:latest
